title: Ice Bro Lite
description: > # this means to ignore newlines until "baseurl:"
  Extended manual for Ice Bro Lite
baseurl: "" # the subpath of your site, e.g. /blog

twitter_username: sakrac
github_username:  sakrac

remote_theme: pages-themes/midnight@v0.2.0

# Build settings
markdown: kramdown

